### ISSUE TITLE
TypeScript types are not being published to npm

### ISSUE THREAD

**Issue by dbalatero** [GoogleChromeLabs/scheduler-polyfill#13]
When I install the package from `npm` (`@next` version, `1.3.0.beta.0`), it has the following structure:

```
❯ ls -al
drwxr-xr-x    - dbalatero 30 Apr 21:34 dist
.rw-r--r--  11k dbalatero 30 Apr 21:34 LICENSE
.rw-r--r-- 1.6k dbalatero 30 Apr 21:34 package.json
.rw-r--r-- 4.2k dbalatero 30 Apr 21:34 README.md

❯ ls -al dist
.rw-r--r-- 9.3k dbalatero 30 Apr 21:34 scheduler-polyfill.js
.rw-r--r--  49k dbalatero 30 Apr 21:34 scheduler-polyfill.js.map
```

When I look in the `package.json` file, I don't see an entry for `"types": "./dist/scheduler.d.ts",`, but I see it in [the latest commit](https://github.com/GoogleChromeLabs/scheduler-polyfill/blob/main/package.json#L7C1-L8C1).

Do you possibly need to push a new beta version?

**Comment by brendankenny** [comment]
Sorry about that, not sure how they weren't included. The new release has them and they should be pulled in when the polyfill is imported.
