### ISSUE TITLE
Add support for background tasks with React Native Hermes  engine

### ISSUE THREAD

**Issue by dlebedynskyi** [GoogleChromeLabs/scheduler-polyfill#5]
React Native Hermes engine does not have support for `MessageChannel`. 

As result following [check will always be `true`](https://github.com/GoogleChromeLabs/scheduler-polyfill/blob/main/src/host-callback.js#L194C40-L194C54) and all tasks will run with `setTimeout`.

However, React Native Hermes engine does have support for `requestIdleCallback`, as such `background` priorities should be able to properly handled. 

I'd suggest change order of checks in https://github.com/GoogleChromeLabs/scheduler-polyfill/blob/main/src/host-callback.js#L190 to better handle edge case. 

I can raise PR for this probably, if change is considered to be reasonable.

**Comment by shaseley** [comment]
Yeah changing that so we independently check `MessageChannel` and `requestIdleCallback()` SGTM. It looks like the delay and `MessageChannel` conditions need to be decoupled. Happy to review a PR if you're interested, or I can draft a fix if not.

**Comment by dlebedynskyi** [comment]
Pushed PR for this one. 

On separate note
is there a plan/ option to set `timeout` for `requestIdleCallback`? or is it not in a spec?

**Comment by shaseley** [comment]
> On separate note is there a plan/ option to set `timeout` for `requestIdleCallback`? or is it not in a spec?

There isn't a `timeout` equivalent for `postTask()`.
