### ISSUE TITLE
Support the scheduler.yield upcoming feature

### ISSUE THREAD

**Issue by calinoracation** [GoogleChromeLabs/scheduler-polyfill#7]
Hey @shaseley, we're about to run a new OT for `scheduler.yield()` and are polyfilling it locally with `yield = scheduler.postTask(empty, opts)`, which seems reasonable. I know there are a few things like signal inheritance it misses, but wondering if you'd be open to a PR adding the basic yield functionality to this polyfill as well?

Reference: https://github.com/WICG/scheduling-apis/blob/main/explainers/yield-and-continuation.md

**Comment by shaseley** [comment]
Hey @calinoracation, that's exciting to hear! I have a [polyfill PR](https://github.com/GoogleChromeLabs/scheduler-polyfill/pull/4) ready to go, but waiting on devrel to have review cycles.

FYI: I'm working on fixing a couple memory issues in the Chrome implementation (which _should_ mostly affects extreme cases). Tracked in https://crbug.com/1469367.

**Comment by calinoracation** [comment]
Oh that's fantastic, I wonder if publishing a `scheduler-polyfill` with the beta tag until then would make sense? Definitely don't want to create more work than necessary though since you already have it queued up.

**Comment by philipwalton** [comment]
> Oh that's fantastic, I wonder if publishing a `scheduler-polyfill` with the beta tag until then would make sense?

Yeah, publishing with a `beta` tag is a good suggestion. @brendankenny let's make sure we do that so people can try the OT without forcing code on existing users.

Also cc: @malchata since that should probably be mentioned in the OT post.
