### ISSUE TITLE
Update yield() instructions in README

### ISSUE THREAD

**Issue by shaseley** [GoogleChromeLabs/scheduler-polyfill#9]
We're planning to release yield as "beta" or "next" tag. Update the README for instructions once we sort that out.

Also, we should update the version when ready to publish -- either the major version in anticipation of release (allowing stable version to claim 1.X) or bump minor version.

**Comment by shaseley** [comment]
@brendankenny - thanks in advance!

**Comment by brendankenny** [comment]
readme instructions are updated and `scheduler.yield` is available in version 1.3.0-beta.0/`scheduler-polyfill@next` on npm
